# config/gateway.config.yml

# http
http:
  port: 8080

# apiEndpoints
apiEndpoints:
  user:
    host: localhost
    paths: "/v1/user/*"
    methods: ["GET", "POST", "PUT", "DELETE"]

  product:
    host: localhost
    paths: "/v1/product/*"
    methods: ["GET", "POST", "PUT", "DELETE"]

# serviceEndpoints
serviceEndpoints:
  userService:
    url: "http://localhost:8006/"

  productService:
    url: "http://localhost:8005/"

# policies
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit

# pipelines
pipelines:
  userPipeline:
    apiEndpoints:
      - user
    policies:
      - proxy:
          - action:
              serviceEndpoint: userService
              changeOrigin: true
  
  productPipeline:
    apiEndpoints:
      - product
    policies:
      - proxy:
          - action:
              serviceEndpoint: productService
              changeOrigin: true
